### ISSUE TITLE
3.1. Création du profil utilisateur

### ISSUE THREAD

**Issue by Soumaya-Qilin** [Soumaya-MAIF/trouve_ton_match_commun#3]
- [ ] Soumaya-MAIF/Projet_Trouve_ton_match#20
- [ ] Soumaya-MAIF/Projet_Trouve_ton_match#21
- [ ] Soumaya-MAIF/Projet_Trouve_ton_match#22
